  DROP TABLE IF EXISTS bronze.erp_sys_item;
CREATE TABLE bronze.erp_sys_item(
    itemean char(13) NOT NULL PRIMARY KEY,
    itemclass smallint NOT NULL,
    section smallint NOT NULL,
    itemgroup smallint NOT NULL,
    department smallint NOT NULL,
    a_name varchar(50) NULL,
    l_name varchar(50) NULL,
    shortname varchar(16) NULL,
    flavor varchar(50) NULL,
    brand smallint NULL,
    producerrno int NULL,
    category smallint NULL,
    referenceno char(30) NULL,
    color smallint NULL,
    size decimal(7, 2) NULL,
    measure smallint NULL,
    hyper_market smallint NULL,
    class_a smallint NULL,
    home_delivery smallint NULL,
    storeinterval smallint NULL,
    shelfinterval smallint NULL,
    goodstype smallint NULL,
    itemtype smallint NULL,
    profit decimal(6, 2) NULL,
    loss_rate decimal(7, 2) NULL,
    expirycheck smallint NULL,
    class_c smallint NULL,
    range_cal smallint NULL,
    ordered_from smallint NULL,
    zone smallint NULL,
    bin_location varchar(20) NULL,
    class_b smallint NULL,
    status smallint NULL,
    statusdate smalldatetime NULL,
    userid int NULL,
    transid smallint NULL,
    pluupd smallint NULL,
    transdate smalldatetime NULL,
    purchase_date smalldatetime NULL,
    whole_sale smallint NULL,
    nationalty smallint NULL,
    big_supermarket smallint NULL,
    module_group smallint NULL,
    module_no smallint NULL,
    basic_item smallint NULL,
    entry_date smalldatetime NULL,
    active smallint NULL,
    price_class smallint NULL,
    transtype smallint NULL,
    item_image varchar(100) NULL,
    sales_tax smallint NULL,
    add_tax smallint NULL,
    Tax_level smallint NULL,
    Season smallint NULL,
    Isdraft smallint NULL,
    IsConsumed smallint NULL,
    Modified_date date NULL,
    Isloaded smallint NULL,
    Loadedby int NULL,
    Loadeddate datetime NULL,
    IsSalesOnLine smallint NULL,
    AdditionalInfo varchar(255) NULL,
    Notes varchar(500) NULL,
    Isserialized smallint NULL,
    IsMaterial_Internal smallint NULL,
    IsMaterial_Outside smallint NULL,
    IsFinalProduct smallint NULL,
    IstemperatureNeed smallint NULL,
    Internal_manufacturing smallint NULL,
    Outside_manufacturing smallint NULL,
    Material smallint NULL,
    Warranty_Period smallint NULL,
    Warranty_Type smallint NULL,
    Warranty_percentage numeric(18, 3) NULL,
    Over_Rate numeric(18, 3) NULL,
    Item_Unit smallint NULL,
    Item_Piece smallint NULL,
    Item_Put_ReorderQty smallint NULL,
    ItemPartNo varchar(100) NULL,
    ISBN varchar(100) NULL,
    Author int NULL,
    Publisher int NULL,
    Createdby int NULL,
    Reserved1 varchar(500) NULL,
    Reserved2 varchar(500) NULL,
    Reserved3 varchar(500) NULL,
    Reserved4 numeric(18, 3) NULL,
    Reserved5 numeric(18, 3) NULL,
    Reserved6 datetime NULL,
    Reserved7 datetime NULL,
    Reserved8 int NULL,
    Reserved9 int NULL,
    Reserved10 int NULL,
    Reserved11 datetime NULL,
    Reserved12 datetime NULL,
    Reserved13 int NULL,
    Reserved14 int NULL,
    Reserved15 int NULL,
    RowVersion timestamp NULL,
    SourceRowVersion bigint NOT NULL,
    CreatedRowVersion bigint NOT NULL,
    CreatedAt int NOT NULL,
    ModifiedAt int NOT NULL,
    DateCreated datetime NOT NULL,
    DateModified datetime NOT NULL,
    Data nvarchar(max) NULL
);
