DROP TABLE IF EXISTS bronze.erp_hd_order_items
CREATE TABLE bronze.erp_hd_order_items(
  [OrderItemId] [bigint] NOT NULL,
	[OrderItemVersion] [smallint] NOT NULL,
	[OrderId] [bigint] NOT NULL,
	[OrderVersion] [smallint] NOT NULL,
	[OrderDate] [datetime] NOT NULL,
	[OrderNo] [int] NOT NULL,
	[TerminalNo] [int] NOT NULL,
	[SessionNo] [smallint] NOT NULL,
	[OrderLineNo] [int] NOT NULL,
	[DocType] [int] NOT NULL,
	[ItemEan] [varchar](20) NOT NULL,
	[Barcode] [varchar](20) NOT NULL,
	[ItemName] [varchar](150) NOT NULL,
	[IsOpenItem] [smallint] NOT NULL,
	[Qty] [decimal](12, 3) NOT NULL,
	[ItemCount] [int] NOT NULL,
	[RetailPrice] [decimal](16, 3) NOT NULL,
	[CostPrice] [decimal](16, 3) NOT NULL,
	[DiscountValue] [decimal](16, 3) NOT NULL,
	[TotalValue] [decimal](16, 3) NOT NULL,
	[TaxValue] [decimal](16, 3) NOT NULL,
	[TaxRate] [decimal](16, 3) NOT NULL,
	[DiscountNo] [int] NULL,
	[DiscountType] [int] NULL,
	[DiscountCoupon] [nvarchar](500) NULL,
	[Unit] [int] NOT NULL,
	[Pieces] [int] NOT NULL,
	[TakerNo] [int] NOT NULL,
	[IsPicked] [smallint] NOT NULL,
	[PickerNo] [int] NULL,
	[PickerName] [nvarchar](150) NULL,
	[PickingTime] [datetime] NULL,
	[IsReturned] [smallint] NOT NULL,
	[ReturnedBy] [int] NULL,
	[ReturnReasonCode] [int] NULL,
	[ReturnReasonName] [nvarchar](500) NULL,
	[PreviousStatusCode] [smallint] NULL,
	[CustomerNo] [int] NOT NULL,
	[ItemClass] [int] NOT NULL,
	[ItemClassName] [nvarchar](100) NOT NULL,
	[ItemSection] [int] NOT NULL,
	[ItemSectionName] [nvarchar](100) NOT NULL,
	[ItemGroup] [int] NOT NULL,
	[ItemGroupName] [nvarchar](100) NOT NULL,
	[ItemDepartment] [int] NOT NULL,
	[ItemDepartmentName] [nvarchar](100) NOT NULL,
	[RegistrationWay] [smallint] NOT NULL,
	[SelectedFrom] [smallint] NOT NULL,
	[CustomerNotes] [nvarchar](1000) NULL,
	[Notes] [nvarchar](1000) NULL,
	[CreatedTime] [datetime] NOT NULL,
	[ModifiedTime] [datetime] NOT NULL,
	[OrderItemData] [nvarchar](max) NULL,
	[RowVersion] [timestamp] NOT NULL,
	[Reserved1] [varchar](500) NULL,
	[Reserved2] [varchar](500) NULL,
	[Reserved3] [varchar](500) NULL,
	[Reserved4] [decimal](18, 3) NULL,
	[Reserved5] [decimal](18, 3) NULL,
	[Reserved6] [datetime] NULL,
	[Reserved7] [datetime] NULL,
	[Reserved8] [int] NULL,
	[Reserved9] [int] NULL,
	[Reserved10] [bigint] NULL,
	[SourceRowVersion] [bigint] NOT NULL,
	[CreatedRowVersion] [bigint] NOT NULL,
	[CreatedAt] [int] NOT NULL,
	[ModifiedAt] [int] NOT NULL,
	[DateCreated] [datetime] NOT NULL,
	[DateModified] [datetime] NOT NULL,
 CONSTRAINT [PK_hd_order_items] PRIMARY KEY CLUSTERED 
(
	[OrderItemId] ASC,
	[OrderItemVersion] ASC)

)

