DROP TABLE IF EXISTS bronze.erp_hd_orders
CREATE TABLE bronze.erp_hd_orders(
	[OrderId] [bigint] NOT NULL,
	[OrderVersion] [smallint] NOT NULL,
	[OrderDate] [datetime] NOT NULL,
	[OrderNo] [int] NOT NULL,
	[TerminalNo] [int] NOT NULL,
	[OrderBranch] [int] NOT NULL,
	[StatusCode] [smallint] NOT NULL,
	[StatusName] [nvarchar](100) NOT NULL,
	[SessionNo] [smallint] NOT NULL,
	[StartTime] [datetime] NOT NULL,
	[EndTime] [datetime] NULL,
	[TotalMinutes] [decimal](9, 2) NOT NULL,
	[TakerNo] [int] NOT NULL,
	[TakerName] [nvarchar](150) NOT NULL,
	[TakingStartTime] [datetime] NOT NULL,
	[TakingEndTime] [datetime] NOT NULL,
	[TakingMinutes] [decimal](9, 2) NOT NULL,
	[PickingStartedBy] [int] NULL,
	[PickingStartedByName] [nvarchar](150) NULL,
	[PickingDocPrintCount] [smallint] NOT NULL,
	[PickerNo] [int] NULL,
	[PickerName] [nvarchar](150) NULL,
	[PickingStartTime] [datetime] NULL,
	[PickingEndTime] [datetime] NULL,
	[PickingMinutes] [decimal](9, 2) NULL,
	[ReviewedBy] [int] NULL,
	[ReviewedByName] [nvarchar](150) NULL,
	[ReviewStartTime] [datetime] NULL,
	[ReviewEndTime] [datetime] NULL,
	[ReviewMinutes] [decimal](9, 2) NULL,
	[DeliveryStartedBy] [int] NULL,
	[DeliveryStartedByName] [nvarchar](150) NULL,
	[PilotNo] [int] NULL,
	[PilotName] [nvarchar](150) NULL,
	[DeliveryStartTime] [datetime] NULL,
	[DeliveryEndTime] [datetime] NULL,
	[DeliveryMinutes] [decimal](9, 2) NULL,
	[DeliveryDocPrintCount] [smallint] NOT NULL,
	[PreviousStatusCode] [smallint] NULL,
	[PreviousStatusName] [nvarchar](100) NULL,
	[IsReturned] [smallint] NOT NULL,
	[ReturnedBy] [int] NULL,
	[ReturnedByName] [nvarchar](150) NULL,
	[ReturnReasonCode] [int] NULL,
	[ReturnReasonName] [nvarchar](500) NULL,
	[ClosedBy] [int] NULL,
	[ClosedByName] [nvarchar](150) NULL,
	[CustomerNo] [int] NOT NULL,
	[CustomerName] [nvarchar](150) NOT NULL,
	[CustomerPhone] [varchar](200) NOT NULL,
	[ShippingAddress] [nvarchar](1000) NOT NULL,
	[OrderLineCount] [smallint] NOT NULL,
	[DiscountValue] [decimal](16, 3) NOT NULL,
	[DiscountNo] [int] NULL,
	[DiscountType] [int] NULL,
	[DiscountCoupon] [nvarchar](500) NULL,
	[PaymentMethod] [smallint] NOT NULL,
	[PaymentMethodDetails] [nvarchar](1000) NULL,
	[DeliveryFees] [decimal](12, 3) NOT NULL,
	[AdditionalFees] [decimal](12, 3) NOT NULL,
	[AdditionalFeesDetails] [nvarchar](1000) NULL,
	[TotalValue] [decimal](16, 3) NOT NULL,
	[InvoiceDate] [datetime] NULL,
	[PosId] [int] NULL,
	[InvoiceNo] [int] NULL,
	[InvoiceActualDate] [datetime] NULL,
	[CashierNo] [int] NULL,
	[CashierName] [nvarchar](150) NULL,
	[CancelledBy] [int] NULL,
	[CancelledByName] [nvarchar](150) NULL,
	[CancelledAtStatusCode] [int] NULL,
	[CancelReasonCode] [int] NULL,
	[CancelReasonName] [nvarchar](150) NULL,
	[CancelTime] [datetime] NULL,
	[OrderSource] [smallint] NOT NULL,
	[CustomerNotes] [nvarchar](1000) NULL,
	[Notes] [nvarchar](1000) NULL,
	[CreatedTime] [datetime] NOT NULL,
	[ModifiedTime] [datetime] NOT NULL,
	[OrderData] [nvarchar](max) NULL,
	[RowVersion] [timestamp] NOT NULL,
	[Reserved1] [varchar](500) NULL,
	[Reserved2] [varchar](500) NULL,
	[Reserved3] [varchar](500) NULL,
	[Reserved4] [decimal](18, 3) NULL,
	[Reserved5] [decimal](18, 3) NULL,
	[Reserved6] [datetime] NULL,
	[Reserved7] [datetime] NULL,
	[Reserved8] [int] NULL,
	[Reserved9] [int] NULL,
	[Reserved10] [bigint] NULL,
	[AddressId] [int] NOT NULL,
	[GovId] [int] NULL,
	[GovName] [nvarchar](500) NULL,
	[TownId] [int] NULL,
	[TownName] [nvarchar](500) NULL,
	[CityId] [int] NULL,
	[CityName] [nvarchar](500) NULL,
	[LocationData] [varchar](2000) NULL,
	[IsFirstOrder] [smallint] NOT NULL,
	[NeedsConfirmation] [smallint] NOT NULL,
	[NeedsConfirmationReasonId] [int] NULL,
	[IsConfirmed] [smallint] NOT NULL,
	[ConfirmedBy] [int] NULL,
	[ConfirmedByName] [nvarchar](500) NULL,
	[ConfirmedTime] [datetime] NULL,
	[IsReviewed] [smallint] NOT NULL,
	[ReviewTime] [datetime] NULL,
	[CommitPrices] [smallint] NOT NULL,
	[CommitPricesDateTo] [datetime] NULL,
	[CommittedPrices] [varchar](max) NULL,
	[DeliveryTime] [datetime] NULL,
	[DeliveryPlace] [int] NULL,
	[AppVersion] [varchar](50) NULL,
	[SourceRowVersion] [bigint] NOT NULL,
	[CreatedRowVersion] [bigint] NOT NULL,
	[CreatedAt] [int] NOT NULL,
	[ModifiedAt] [int] NOT NULL,
	[DateCreated] [datetime] NOT NULL,
	[DateModified] [datetime] NOT NULL,
 CONSTRAINT [PK_hd_orders] PRIMARY KEY CLUSTERED 
(
	[OrderId] ASC,
	[OrderVersion] ASC)

)
