    DROP TABLE IF EXISTS bronze.erp_sys_branch;
CREATE TABLE bronze.erp_sys_branch (
    company smallint NOT NULL,
    sector smallint NOT NULL,
    region smallint NOT NULL,
    branch int NOT NULL primary key,
    branchtype smallint NOT NULL,
    activity smallint NULL,
    a_name char(50) NULL,
    l_name char(50) NULL,
    country smallint NULL,
    govern smallint NULL,
    a_address char(50) NULL,
    l_address char(50) NULL,
    a_manager char(30) NULL,
    l_manager char(30) NULL,
    comm_no char(20) NULL,
    tax_file_no char(20) NULL,
    taxunit smallint NULL,
    tax_status smallint NULL,
    phone1 char(15) NULL,
    phone2 char(15) NULL,
    fax char(15) NULL,
    email char(50) NULL,
    area decimal(6, 2) NULL,
    ownership smallint NULL,
    a_ownername char(50) NULL,
    l_ownername char(50) NULL,
    rental_value decimal(10, 3) NULL,
    rental_date smalldatetime NULL,
    storage_area decimal(6, 2) NULL,
    license_date smalldatetime NULL,
    status smallint NULL,
    me decimal(1, 0) NULL,
    branch_weight decimal(7, 2) NULL,
    waves_no smallint NULL,
    store_class smallint NULL,
    warehouse int NULL,
    openning smallint NULL,
    transdate smalldatetime NULL,
    mobile char(15) NULL,
    heirarchy smallint NULL,
    p_sector smallint NULL,
    tax_status_date smalldatetime NULL,
    last_modified_time datetime NULL
);
